---
title: "ar-notebook"
format: html
editor: visual
---

## Loading packages

```{r}
library(ggplot2)
library(tidyverse)
library(lubridate)

library(cmdstanr)
library(posterior)
library(bayesplot)
```

### Testing cmdstanr on simulated data

```{r}
fit <- cmdstanr_example("logistic", chains = 2)
fit$summary()
```

### Simulating AR(1) data

```{r}
phi <- c(0.5, 0.25, 0.2)
roots <- polyroot(c(1, -phi))
magnitudes <- Mod(roots)
magnitudes

set.seed(123)
ar3_data <- arima.sim(model = list(ar = phi), n = 200, sd = 10)
```

```{r}
plot(ar3_data)
```


### Fitting AR model to simulated data

```{r}
stan_data <- list(
  T       = length(ar3_data),
  Y       = as.numeric(ar3_data),
  p       = 3,
  sigma_sd = sd(as.numeric(ar3_data)),
  phi_sd   = 0.5
)


mod <- cmdstan_model(
  "models/ar.stan",
  stanc_options = list("O1", "warn-pedantic" = TRUE)
)

fit <- mod$sample(
  data = stan_data
)
```

### Posterior analysis of model

```{r}
fit$summary(c("alpha", "phi", "sigma"))
```

```{r}
yrep <- fit$draws("Y_rep", format = "draws_matrix")
lags <- 1:16

acf_of  <- function(v) acf(v, lag.max = max(lags), plot = FALSE)$acf[lags + 1]
rep_acf <- t(apply(yrep, 1, acf_of))
obs_acf <- acf_of(as.numeric(ar3_data))

ppc_intervals(y = obs_acf, yrep = rep_acf, x = lags) +
  ggplot2::labs(x = "Lag", y = "Autocorrelation")

acf(ar3_data, lag.max = 16, plot = FALSE)$acf[1:16 + 1]
```

### Fitting ARR2 model to simmed data

```{r}
stan_data <- list(
  T       = length(ar3_data),
  Y       = as.numeric(ar3_data),
  p       = 3,
  sigma_sd = sd(as.numeric(ar3_data)),
  phi_sd   = 0.5,
  cons = rep(1, 3),
  mean_R2 = 0.6,
  prec_R2 = 10.5
)


mod <- cmdstan_model(
  "models/arr2.stan",
  stanc_options = list("O1", "warn-pedantic" = TRUE)
)

fit <- mod$sample(
  data = stan_data
)
```

### Posterior analysis of model

```{r}
fit$summary(c("alpha", "phi", "sigma"))
```

```{r}
ysim <- fit$draws("Y_sim", format = "draws_matrix")
lags <- 1:16

acf_of  <- function(v) acf(v, lag.max = max(lags), plot = FALSE)$acf[lags + 1]
sim_acf <- t(apply(ysim, 1, acf_of))
obs_acf <- acf_of(as.numeric(ar3_data))

ppc_intervals(y = obs_acf, yrep = sim_acf, x = lags) +
  ggplot2::labs(x = "Lag", y = "Autocorrelation")

acf(ar3_data, lag.max = 16, plot = FALSE)$acf[1:16 + 1]
```

### Loading UMich data and doing EDA

```{r}
umich <- read.csv("../../data/raw/sca-table1-on-2026-Aug-30.csv")

umich$date <- make_date(year = umich$Year, month = umich$Month, day = 1)

umich <- umich %>%
  mutate(ld_index = log(Index) - lag(log(Index))) %>%
  slice(-1) %>%
  relocate(date)

ggplot(umich, aes(date, Index)) +
  geom_line()

ggplot(umich, aes(date, ld_index)) +
  geom_line()

```

```{r}
stan_data <- list(
  T       = nrow(umich),
  Y       = umich$Index,
  p       = 4,
  sigma_sd = sd(umich$Index),
  phi_sd   = 0.5
)


mod <- cmdstan_model(
  "models/ar.stan",
  stanc_options = list("O1", "warn-pedantic" = TRUE)
)

fit <- mod$sample(
  data            = stan_data,
  seed            = 20260830,
  chains          = 4,
  parallel_chains = 4,
  iter_warmup     = 1000,
  iter_sampling   = 1000,
  adapt_delta     = 0.9,
  refresh         = 500
)
```

```{r}
fit$diagnostic_summary()
fit$summary(c("alpha", "phi", "sigma"))
```

```{r}
dir.create("fits", showWarnings = FALSE)
fit$save_output_files(dir = "fits", basename = "ar4",
                      timestamp = FALSE, random = FALSE)
```

```{r}
ysim <- fit$draws("Y_sim", format = "draws_matrix")   # draws × T
lags <- 1:16

acf_of  <- function(v) acf(v, lag.max = max(lags), plot = FALSE)$acf[lags + 1]
sim_acf <- t(apply(ysim, 1, acf_of))                  # draws × 16
obs_acf <- acf_of(umich$Index)                              # length 16

ppc_intervals(y = obs_acf, yrep = sim_acf, x = lags) +
  ggplot2::labs(x = "Lag", y = "Autocorrelation")
```

```{r}
stan_data <- list(
  T       = nrow(umich),
  Y       = umich$Index,
  p       = 4,
  sigma_sd = sd(umich$Index),
  phi_sd   = 0.5,
  cons = rep(1, 4),
  mean_R2 = 0.75,
  prec_R2 = 3
)


mod <- cmdstan_model(
  "models/arr2.stan",
  stanc_options = list("O1", "warn-pedantic" = TRUE)
)

fit <- mod$sample(
  data            = stan_data,
  seed            = 20260830,
  chains          = 4,
  parallel_chains = 4,
  iter_warmup     = 1000,
  iter_sampling   = 1000,
  adapt_delta     = 0.9,
  refresh         = 500
)
```

```{r}
fit$diagnostic_summary()
fit$summary(c("alpha", "phi", "sigma"))
```

```{r}
dir.create("fits", showWarnings = FALSE)
fit$save_output_files(dir = "fits", basename = "arr2",
                      timestamp = FALSE, random = FALSE)
```

```{r}
library(bayesplot)

ysim <- fit$draws("Y_sim", format = "draws_matrix")   # draws × T
lags <- 1:16

acf_of  <- function(v) acf(v, lag.max = max(lags), plot = FALSE)$acf[lags + 1]
sim_acf <- t(apply(ysim, 1, acf_of))                  # draws × 16
obs_acf <- acf_of(umich$Index)                              # length 16

ppc_intervals(y = obs_acf, yrep = sim_acf, x = lags) +
  ggplot2::labs(x = "Lag", y = "Autocorrelation")
```
