---
title: "VAR(2) with Conjugate Priors"
format: html
editor: visual
---

```{r}
library(ggplot2)
```

We're going to run some Bayesian VAR(2) models in R (conjugate priors and Minnesota with fixed innovation matrix).

```{r}
Y <- as.matrix(read.csv("notebooks/simdata/Y_sim.csv", header = FALSE, col.names = c("y1", "y2")))

T <- nrow(Y) # Number of time periods
K <- ncol(Y) # Number of variables
P <- 2

Y_eff <- Y[(P+1):T, ]                    
X <- cbind(1,
           Y[P:(T-1), ],                 
           Y[1:(T-2), ])                 
                                      
```

This block sets the "known" sigma's from the data by taking the standard deviation of the residuals for each of the 2 univariate AR processes:

```{r}
lambda <- 0.2  
theta  <- 0.2  
alpha    <- 1   
delta  <- rep(1, K)
sigma <- numeric(K)

for (k in 1:K) {
  sigma[k] <- sqrt(arima(Y[, k], order = c(P, 0, 0))$sigma2)
}

M <- K * P + 1
B_post     <- matrix(0, nrow = M, ncol = K)
V_post_lst <- vector("list", K)

for (j in 1:K) {
    # Step 2: build gamma_bar, tau
    gamma_bar <- numeric(M)
    tau       <- numeric(M)
    tau[1]    <- 1e6

    for (l in 1:P) {
      for (r in 1:K) {
        pos <- 1 + (l - 1) * K + r
        if (r == j) {
          gamma_bar[pos] <- if (l == 1) delta[j] else 0
          tau[pos]       <- lambda / l^alpha
        } else {
          gamma_bar[pos] <- 0
          tau[pos]       <- (lambda * theta * sigma[j]) / (l^alpha * sigma[r])
        }
      }
    }
  
    # Step 3: build R_j, r_j
    R_j <- diag(sigma[j] / tau)        # M x M diagonal
    r_j <- gamma_bar * (sigma[j] / tau) # length M
    
    # Step 4: compute posterior moments
    XtX_post   <- crossprod(X) + crossprod(R_j)
    gamma_post <- solve(XtX_post, crossprod(X, Y_eff[, j]) + crossprod(R_j, r_j))
    V_post     <- sigma[j]^2 * solve(XtX_post)
    
    B_post[, j]     <- gamma_post
    V_post_lst[[j]] <- V_post
}

print(B_post)
```

```{r}
conj_litter <- function(Y, P, lambda, theta, alpha = 1) {
  
  T <- nrow(Y) # Number of time periods
  K <- ncol(Y) # Number of variables
  P <- P # Number of lags

  Y_eff <- Y[(P+1):T, ]                    
  X <- cbind(1,
            Y[P:(T-1), ],                 
            Y[1:(T-2), ])  
  
  lambda <- lambda  
  theta  <- theta  
  alpha  <- alpha   
  delta  <- rep(1, K)
  sigma <- numeric(K)
  
  for (k in 1:K) {
    sigma[k] <- sqrt(arima(Y[, k], order = c(P, 0, 0))$sigma2)
  }

  M <- K * P + 1
  B_post     <- matrix(0, nrow = M, ncol = K)
  V_post_lst <- vector("list", K)

  for (j in 1:K) {
      # Step 2: build gamma_bar, tau
      gamma_bar <- numeric(M)
      tau       <- numeric(M)
      tau[1]    <- 1e6

      for (l in 1:P) {
        for (r in 1:K) {
          pos <- 1 + (l - 1) * K + r
          if (r == j) {
            gamma_bar[pos] <- if (l == 1) delta[j] else 0
            tau[pos]       <- lambda / l^alpha
          } else {
            gamma_bar[pos] <- 0
            tau[pos]       <- (lambda * theta * sigma[j]) / (l^alpha * sigma[r])
          }
        }
      }
    
      # Step 3: build R_j, r_j
      R_j <- diag(sigma[j] / tau)        # M x M diagonal
      r_j <- gamma_bar * (sigma[j] / tau) # length M
      
      # Step 4: compute posterior moments
      XtX_post   <- crossprod(X) + crossprod(R_j)
      gamma_post <- solve(XtX_post, crossprod(X, Y_eff[, j]) + crossprod(R_j, r_j))
      V_post     <- sigma[j]^2 * solve(XtX_post)
      
      B_post[, j]     <- gamma_post
      V_post_lst[[j]] <- V_post
  }
  return(t(B_post))
}

```

```{r}

lambda_check <- c(0.1, 0.2, 0.3, 0.4, 0.5)
B_post_list <- vector(mode = "list", length = length(lambda_check))

for (i in 1:length(lambda_check)) {
   coef <- conj_litter(Y, P = 2, lambda = lambda_check[i], theta = 0.2, alpha = 1)

   B_post_list[[i]] <- coef
}

B_post_list[1]
```

```{r}
 
```